import { useMemo, useState } from "react";
import { CalendarDays, Download, Filter, History as HistoryIcon, Search, SlidersHorizontal } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { LiquidGlassCard } from "@/components/visual/LiquidGlassCard";
import { LiveTelemetryChart } from "@/components/EngineeringCharts";

export default function History() {
  const snapshot = trpc.dashboard.snapshot.useQuery({ deviceKey: "array-a" });
  const [range, setRange] = useState("60 samples");
  const history = (snapshot.data?.history ?? []) as Array<{ timestampMs: number; vPv: number; iPv: number; pPv: number; vMp: number; iPh: number; duty: number; efficiency: number; scenarioCode?: string }>;
  const latest = history[history.length - 1];
  const averagePower = useMemo(() => history.length ? history.reduce((sum, item) => sum + item.pPv, 0) / history.length : 0, [history]);
  return <div className="subpage"><div className="subpage-heading"><div><span className="eyebrow">ARCHIVE / TELEMETRY BUFFER</span><h1>Telemetry history</h1><p>Every accepted frame is stored against the Array A device record for post-demo validation.</p></div><div className="subpage-actions"><button className="button subtle"><Download size={14} /> export CSV</button><button className="button icon"><Filter size={15} /></button></div></div>
    <div className="metric-strip"><LiquidGlassCard><small>BUFFERED SAMPLES</small><strong>{history.length || 0}<em>/ 60</em></strong><span><HistoryIcon size={13} /> rolling window</span></LiquidGlassCard><LiquidGlassCard><small>MEAN P_pv</small><strong>{averagePower.toFixed(1)}<em>W</em></strong><span>current range</span></LiquidGlassCard><LiquidGlassCard><small>LATEST EFFICIENCY</small><strong>{(latest?.efficiency ?? 96.8).toFixed(1)}<em>%</em></strong><span>η_MPPT</span></LiquidGlassCard><LiquidGlassCard><small>ACTIVE SCENARIO</small><strong>{latest?.scenarioCode ?? "S5"}</strong><span>tracking window</span></LiquidGlassCard></div>
    <LiquidGlassCard className="history-chart"><div className="panel-heading"><div><span className="eyebrow">PERSISTED SERIES</span><h2>Stored telemetry stream</h2></div><div className="segmented"><button className={range === "60 samples" ? "selected" : ""} onClick={() => setRange("60 samples")}>60 samples</button><button className={range === "1 hour" ? "selected" : ""} onClick={() => setRange("1 hour")}>1 hour</button><button className={range === "24 hours" ? "selected" : ""} onClick={() => setRange("24 hours")}>24 hours</button></div></div><LiveTelemetryChart telemetry={history.length ? history.map((item) => ({ timestampMs: item.timestampMs, vPv: item.vPv, iPv: item.iPv, pPv: item.pPv, vMp: item.vMp, iPh: item.iPh, duty: item.duty, efficiency: item.efficiency })) : []} /></LiquidGlassCard>
    <LiquidGlassCard className="data-panel"><div className="panel-heading"><div><span className="eyebrow">RAW FRAME LOG</span><h2>Recent samples</h2></div><div className="search-box"><Search size={14} /><input placeholder="Filter by scenario or time" aria-label="Filter telemetry samples" /></div></div><div className="table-wrap"><table><thead><tr><th>Timestamp</th><th>Scenario</th><th>V_pv</th><th>I_pv</th><th>P_pv</th><th>V_mp</th><th>I_ph</th><th>Duty</th><th>η_MPPT</th></tr></thead><tbody>{history.slice().reverse().slice(0, 12).map((item) => <tr key={String(item.timestampMs)}><td><CalendarDays size={13} />{new Date(item.timestampMs).toLocaleTimeString()}</td><td><span className="table-tag">{item.scenarioCode}</span></td><td>{item.vPv.toFixed(2)} V</td><td>{item.iPv.toFixed(2)} A</td><td className="highlight">{item.pPv.toFixed(1)} W</td><td>{item.vMp.toFixed(2)} V</td><td>{item.iPh.toFixed(2)} A</td><td>{(item.duty * 100).toFixed(1)}%</td><td>{item.efficiency.toFixed(1)}%</td></tr>)}{!history.length ? <tr><td colSpan={9} className="table-empty">No persisted telemetry yet. Connect the ESP32 or allow demo frames to populate the database.</td></tr> : null}</tbody></table></div><div className="panel-foot"><span><SlidersHorizontal size={13} /> schema locked to firmware telemetry contract</span><span>{range} · UTC stored / local display</span></div></LiquidGlassCard></div>;
}
