import { Area, AreaChart, CartesianGrid, ComposedChart, Line, LineChart, ReferenceArea, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, Radio, Zap } from "lucide-react";
import { LiquidGlassCard } from "@/components/visual/LiquidGlassCard";

type Sample = { timestampMs: number; vPv: number; iPv: number; pPv: number; vMp: number; iPh: number; duty: number; efficiency: number };
const colors = { cyan: "#72e3d2", violet: "#b98dfd", amber: "#f2c46d", blue: "#7fd7f1", red: "#ef7892" };
const tooltip = { background: "#0a1822", border: "1px solid rgba(127, 194, 218, .2)", borderRadius: 8, color: "#d9edf2", fontSize: 11 };
const tick = { fill: "#68818e", fontSize: 10 };
const grid = "rgba(124, 164, 181, .12)";

function ChartCard({ eyebrow, title, tag, children, className = "" }: { eyebrow: string; title: string; tag: string; children: React.ReactNode; className?: string }) {
  return <LiquidGlassCard className={`chart-card ${className}`}><div className="chart-card-head"><div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3></div><span className="chart-tag">{tag}</span></div>{children}</LiquidGlassCard>;
}
function Legend({ items }: { items: { label: string; color: string }[] }) { return <div className="chart-legend">{items.map((item) => <span key={item.label}><i style={{ background: item.color }} />{item.label}</span>)}</div>; }

function comparisonData(telemetry: Sample[]) { const live = telemetry.slice(-28); return (live.length ? live : Array.from({ length: 28 }, (_, i) => ({ timestampMs: i, vPv: 31, iPv: 7, pPv: 216 + Math.sin(i / 4) * .5, vMp: 31, iPh: 7, duty: .61, efficiency: 97 }))).map((item, index) => ({ sample: index + 1, matlab: 216.2 + Math.sin(index / 4) * .7, esp32: item.pPv })); }
const pvCurve = [{ voltage: 0, power: 0 }, { voltage: 5, power: 48 }, { voltage: 10, power: 108 }, { voltage: 15, power: 158 }, { voltage: 20, power: 195 }, { voltage: 25, power: 214 }, { voltage: 28, power: 219 }, { voltage: 31, power: 216 }, { voltage: 34, power: 195 }, { voltage: 37, power: 152 }, { voltage: 40, power: 83 }, { voltage: 43, power: 0 }];
const responseData = Array.from({ length: 26 }, (_, i) => ({ ms: i * 5, lower: 214, upper: 220, response: 216 + Math.exp(-i / 3) * Math.sin(i * 1.35) * 3.2 }));

export function EkfPoChart({ telemetry }: { telemetry: Sample[] }) { return <ChartCard eyebrow="LIVE / REFERENCE" title="MATLAB reference vs ESP32 live" tag="P_pv"><div className="chart-visual tall"><ResponsiveContainer><ComposedChart data={comparisonData(telemetry)}><CartesianGrid stroke={grid} vertical={false} /><XAxis dataKey="sample" tick={tick} axisLine={false} tickLine={false} /><YAxis domain={[208, 222]} tick={tick} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} /><Line type="monotone" dataKey="matlab" stroke={colors.blue} strokeWidth={2} dot={false} name="MATLAB reference" /><Line type="monotone" dataKey="esp32" stroke={colors.cyan} strokeWidth={2.2} dot={false} name="ESP32 live" /></ComposedChart></ResponsiveContainer></div><div className="chart-foot"><Legend items={[{ label: "MATLAB reference", color: colors.blue }, { label: "ESP32 live", color: colors.cyan }]} /><span>watts · last 28 samples</span></div></ChartCard>; }

function GaugeRing({ value, label, number, color }: { value: number; label: string; number: string; color: string }) { const radius = 42; const circumference = 2 * Math.PI * radius; return <div className="gauge-wrap"><svg viewBox="0 0 104 104"><circle cx="52" cy="52" r={radius} fill="none" stroke="rgba(125,161,177,.14)" strokeWidth="7" /><circle cx="52" cy="52" r={radius} fill="none" stroke={color} strokeWidth="7" strokeLinecap="round" strokeDasharray={`${value / 100 * circumference} ${circumference}`} transform="rotate(-90 52 52)" /></svg><strong>{number}</strong><span>{label}</span></div>; }
export function RippleChart({ telemetry }: { telemetry: Sample[] }) { const values = telemetry.slice(-18).map((item) => item.pPv); const mean = values.reduce((sum, value) => sum + value, 0) / Math.max(values.length, 1); const ripple = mean ? ((Math.max(...values, mean) - Math.min(...values, mean)) / mean) * 100 : 0; const matlabReference = .8; const liveGauge = Math.min(100, ripple / 5 * 100); const referenceGauge = matlabReference / 5 * 100; const liveGood = ripple <= 1; return <ChartCard eyebrow="RIPPLE ANALYSIS" title="MPPT ripple" tag="LIVE"><div className="gauge-panel"><GaugeRing value={referenceGauge} color={colors.blue} label="MATLAB reference" number={`${matlabReference.toFixed(1)}%`} /><div className="gauge-divider" /><GaugeRing value={liveGauge} color={liveGood ? colors.cyan : colors.red} label="ESP32 live" number={`${ripple.toFixed(2)}%`} /></div><div className="chart-foot"><span className={liveGood ? "good" : "warning-text"}><span className={`status-dot ${liveGood ? "" : "red"}`} /> {liveGood ? "within ≤1% target" : "above 1% target"}</span><span><Zap size={12} /> measured peak-to-peak</span></div></ChartCard>; }
export function PvCurveChart() { return <ChartCard eyebrow="PV CHARACTERISTIC" title="V / P-V characteristic" tag="STATIC CURVE"><div className="chart-visual"><ResponsiveContainer><LineChart data={pvCurve}><CartesianGrid stroke={grid} vertical={false} /><XAxis dataKey="voltage" tick={tick} axisLine={false} tickLine={false} unit="V" /><YAxis domain={[0, 240]} tick={tick} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} /><Line type="monotone" dataKey="power" stroke={colors.blue} strokeWidth={2.2} dot={false} name="P-V curve" /></LineChart></ResponsiveContainer></div><div className="chart-foot"><span>V_pv · V</span><span>P_pv · W</span></div></ChartCard>; }
export function EfficiencyChart({ efficiency }: { efficiency: number }) { return <ChartCard eyebrow="CONTROLLER PERFORMANCE" title="η_MPPT efficiency" tag="OVERALL"><div className="efficiency-panel"><div className="efficiency-ring" style={{ "--ring": `${Math.max(0, Math.min(360, efficiency * 3.6))}deg` } as React.CSSProperties}><strong>{efficiency.toFixed(1)}<small>%</small></strong><span>η_MPPT</span></div><div><span className="metric-label"><Radio size={13} /> controller efficiency</span><strong className="metric-good">stable</strong><p>Persistent calculation from the current S5 tracking window.</p></div></div></ChartCard>; }
export function LiveTelemetryChart({ telemetry }: { telemetry: Sample[] }) { const data = telemetry.slice(-34).map((item, index) => ({ sample: index, voltage: item.vPv, power: item.pPv, iph: item.iPh })); return <ChartCard eyebrow="REAL-TIME SIGNALS" title="Live telemetry" tag="STREAMING"><div className="chart-visual tall"><ResponsiveContainer><LineChart data={data}><CartesianGrid stroke={grid} vertical={false} /><XAxis dataKey="sample" tick={tick} axisLine={false} tickLine={false} /><YAxis yAxisId="left" domain={[29.5, 33]} tick={tick} axisLine={false} tickLine={false} /><YAxis yAxisId="right" orientation="right" domain={[0, 240]} tick={tick} axisLine={false} tickLine={false} /><YAxis yAxisId="iph" domain={[6, 8]} hide /><Tooltip contentStyle={tooltip} /><Line yAxisId="left" type="monotone" dataKey="voltage" stroke={colors.blue} strokeWidth={1.8} dot={false} name="V_pv" /><Line yAxisId="right" type="monotone" dataKey="power" stroke={colors.amber} strokeWidth={1.8} dot={false} name="P_pv" /><Line yAxisId="iph" type="monotone" dataKey="iph" stroke={colors.violet} strokeWidth={1.5} dot={false} name="I_ph" /></LineChart></ResponsiveContainer></div><div className="chart-foot"><Legend items={[{ label: "V_pv", color: colors.blue }, { label: "P_pv", color: colors.amber }, { label: "I_ph", color: colors.violet }]} /><span>last 34 samples</span></div></ChartCard>; }
export function DutyChart({ duty }: { duty: number }) { const data = Array.from({ length: 18 }, (_, index) => ({ sample: index, duty: duty * 100 + Math.sin(index / 2.7) * .7 })); return <ChartCard eyebrow="SECONDARY CONTEXT" title="Duty cycle" tag="AREA"><div className="chart-visual small"><ResponsiveContainer><AreaChart data={data}><defs><linearGradient id="duty-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={colors.violet} stopOpacity={.34} /><stop offset="100%" stopColor={colors.violet} stopOpacity={.02} /></linearGradient></defs><CartesianGrid stroke={grid} vertical={false} /><XAxis dataKey="sample" tick={tick} axisLine={false} tickLine={false} /><YAxis domain={[55, 66]} tick={tick} axisLine={false} tickLine={false} unit="%" /><Tooltip contentStyle={tooltip} /><Area type="monotone" dataKey="duty" stroke={colors.violet} fill="url(#duty-fill)" strokeWidth={1.8} name="Duty" /></AreaChart></ResponsiveContainer></div><div className="chart-foot"><span>current controller duty</span><strong>{(duty * 100).toFixed(1)}%</strong></div></ChartCard>; }
export function ResponseBandChart() { return <ChartCard eyebrow="S2 / TRANSIENT RESPONSE" title="Response-time band" tag="TARGET <100 MS"><div className="chart-visual small"><ResponsiveContainer><ComposedChart data={responseData}><CartesianGrid stroke={grid} vertical={false} /><XAxis dataKey="ms" tick={tick} axisLine={false} tickLine={false} unit="ms" /><YAxis domain={[208, 222]} tick={tick} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} /><ReferenceArea y1={214} y2={220} fill={colors.cyan} fillOpacity={.08} strokeOpacity={0} /><Area type="monotone" dataKey="upper" stroke="none" fill={colors.cyan} fillOpacity={.05} name="target band" /><Line type="monotone" dataKey="response" stroke={colors.amber} strokeWidth={1.8} dot={false} name="actual response" /></ComposedChart></ResponsiveContainer></div><div className="chart-foot"><span><i className="legend-inline cyan" /> target band</span><span>settled <strong>75 ms</strong></span></div></ChartCard>; }
export function ChartEmpty({ label }: { label: string }) { return <div className="chart-empty"><Activity size={16} /> {label}</div>; }
